apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-cool-application-deployment
  labels:
    app: my-cool-application
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-cool-application
  template:
    metadata:
      labels:
        app: my-cool-application
    spec:
      containers:
      - name: my-cool-application
        image: 257906693240.dkr.ecr.us-east-1.amazonaws.com/my-cool-application:latest
        ports:
        - containerPort: 80

